const acceleratorRows = [
    {
        "id":  "acc-001",
        "include":  false,
        "module":  "Central Business Configuration",
        "productArea":  "Scoping",
        "functionality":  "Scope Activation in Public Cloud",
        "gapType":  "Product Gap",
        "gapDetails":  "If we have parallel ledgers, the Scope items are to be finalised in the DDA stage itself. Once scope items are deployed and the config is moved to DEV, there is no chance of adding new scope items.",
        "businessGap":  "For  implementations with parallel ledgers, it is essential to finalize the required scope items during the Digital Discovery Assessment (DDA) phase. \nOnce the scope items are deployed and configurations are moved to the development environment, adding new scope items later is not possible.",
        "accelerator":  "",
        "asset":  "Documentation of all missing scope item required for initial activation",
        "assetBusiness":  "Develop a centralized document mapping all required scope items to their respective business processes to ensure completeness and prevent gaps during initial activation.",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-002",
        "include":  false,
        "module":  "Central Business Configuration",
        "productArea":  "Scoping",
        "functionality":  "FYV \u0026 Alternate FYV",
        "gapType":  "Product Gap",
        "gapDetails":  "Incorrect Fiscal year variant updates during scoping can lead to re-prevision",
        "businessGap":  "Incorrect updates to the fiscal year variant during scoping  leads to  re-previsioning, potentially impacting initial setup and reporting accuracy.",
        "accelerator":  "",
        "asset":  "Documentation on Fiscal Year Varaint \u0026 Alternate FYV to help customer chose the correct FYV which helps to avoid reprovisioning",
        "assetBusiness":  "Create documentation on the Fiscal Year Variant (FYV) and Alternate FYV to guide customers in selecting the correct variant, which helps  to avoid reprovisioning.",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-003",
        "include":  false,
        "module":  "Central Business Configuration",
        "productArea":  "Org Structure",
        "functionality":  "IFRS vs LOCAL GAAP vs US GAAP",
        "gapType":  "Knowledge Base",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Documentation to help customers choose the Parallel Ledger concept in Cloud \u0026 how not selecting the right option can either limit solution or lead to re-provision",
        "assetBusiness":  "Create a document on IFRS, Local GAAP, and US GAAP to guide customers in selecting the appropriate Parallel Ledger concept in the Cloud, highlighting how incorrect choices can limit functionality or necessitate reprovisioning.",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-004",
        "include":  false,
        "module":  "Central Business Configuration",
        "productArea":  "Org Structure",
        "functionality":  "5W2 - Group Valuation",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "I hope we can include it  with Row # 2",
        "accelerator":  "",
        "asset":  "Documentation on using additional Parallel ledger to implement group valuation using the Universal Parallel Accounting \u0026  how not selecting the right option can either limit solution or lead to re-provision",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-005",
        "include":  false,
        "module":  "Data Migration",
        "productArea":  "Data Migration using Staging Tables approach",
        "functionality":  "",
        "gapType":  "",
        "gapDetails":  "Data Migration Design for S4H PC",
        "businessGap":  "Data Migration Design in S4H PC to share best practices,  address knowledge gaps for accurate, efficient data transfer",
        "accelerator":  "",
        "asset":  "Comprehensive General Data Migration design to help customers accelerate:\n\nGL Balances \u0026 Open Item  \nHistorical Balances \u0026 Movements \nAsset Master \u0026 Transactions\nMaterial Inventory Balances\nTax GL Balances\nForex Balances\nAUC Assets \u0026 Transactions\nCash Balances at Liquidity \u0026 Forecasting Level",
        "assetBusiness":  "Leverage knowledge gained from recent data migration and  create a comprehensive document \"General Data Migration Design\" helps accelerating future implementations across different data  migrations. \nEx..\nGL Balances \u0026 Open Item  \nHistorical Balances \u0026 Movements \nAsset Master \u0026 Transactions\nMaterial Inventory Balances\nTax GL Balances\nForex Balances\nAUC Assets \u0026 Transactions\nCash Balances at Liquidity \u0026 Forecasting Level",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-006",
        "include":  false,
        "module":  "Data Migration",
        "productArea":  "Data Migration using Staging Tables approach",
        "functionality":  "",
        "gapType":  "Knowledge Gap",
        "gapDetails":  "Lease Data Migration by SAP has no relevant details required to support Data Mig",
        "businessGap":  "Currently, there is no relevant documentation available from SAP to guide Lease Data Migration, creating a knowledge gap for implementation teams",
        "accelerator":  "",
        "asset":  "Comprehensive REFX Data Migration solution along with Product Bug Fixes",
        "assetBusiness":  "A Document with comprehensive REFX Data Migration approach, including product bug fixes \u0026 best practices which ensure accurate, efficient lease data transfer in future implementations",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-007",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-GL",
        "functionality":  "Chart of Accounts",
        "gapType":  "Product Gap",
        "gapDetails":  "Lacking documentation on how to Adapt PC COA to Customer requirements",
        "businessGap":  "Currently no documentation available on how to adapt the Public Cloud Chart of Accounts (COA) to meet specific customer requirements.",
        "accelerator":  "",
        "asset":  "Comprehensive Documentation on how to adapt SAP\u0027s Pre Delivered Chart on cloud for customers own business requirements",
        "assetBusiness":  "Document how to adapt SAP’s pre-delivered Cloud COA for customer-specific requirements to enable efficient implementation.",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-008",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-GL",
        "functionality":  "Substitutions/Validations",
        "gapType":  "Product Gap",
        "gapDetails":  "Substitutions \u0026 Validations in SAP are heavily restricted by SAP Cloud. Customers are not allowed to update most of the ACDOCA fields\n resulting in missing functionalities. \n\nPrebuilt . Substution / cash flow s",
        "businessGap":  "As per IFRS tool - BP multiple banks acc -  Validation rule - to determine which bank acc - make partner type",
        "accelerator":  "Define a list of Common Sub/Val defined for several customer across industries which are a bare minimum requirement for implementing a Public Cloud Product",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "In-app extensibility from Custom Fields \u0026 Logic app to extend the required fields for Sub/Val",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-009",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FICO",
        "functionality":  "Fiori Tiles for Important Tables in SAP",
        "gapType":  "Product Gap",
        "gapDetails":  "Custom CDS Views for Tables - e.g., ACDOCA",
        "businessGap":  "",
        "accelerator":  "Tables and Fields cannot be opted like on-prem",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "Need to search for CDS Views for relevant, but most of them are not available in PC",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-010",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-GL",
        "functionality":  "Global Hierarchies",
        "gapType":  "Product Gap",
        "gapDetails":  "Lack of Documentation on Usage of Global Hierarchies in GL, PCA, CCA \u0026 how Global hierarchies work in Tandem with Standard Hierarchies",
        "businessGap":  "Lack of  documentation on how Global Hierarchies are used in GL, PCA, and CCA, and how Global Hierarchies  interact with Standard Hierarchies, creating a knowledge gap for implementation teams.",
        "accelerator":  "",
        "asset":  "Detailed documentation of Global Hierarchies \u0026 Standard hierarchy setup options for cloud environment, utilising Global Hierarchies to support the reporting options on cloud",
        "assetBusiness":  "Create detailed documentation on Global Hierarchies and Standard Hierarchy setup options in the Cloud, highlighting how to leverage Global Hierarchies to support reporting requirements effectively",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-011",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-GL",
        "functionality":  "YOY Comparison Reports",
        "gapType":  "",
        "gapDetails":  "Product GAP in SAP offerings",
        "businessGap":  "No standard SAP solution exists for Year-over-Year Comparison Reports, highlighting a product gap for financial analysis. --  B/S YOY - / Current yer to date Vs Budget , Previous month to this month",
        "accelerator":  "Custom Analytical Queries \u0026 Custom Fiori apps to support the YOY reporting with Multi Dimensional Parameters for Reporting",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-012",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-GL",
        "functionality":  "Reset Transaction Data",
        "gapType":  "",
        "gapDetails":  "Product GAP on using Transaction Reset in Cloud \u0026 bugs",
        "businessGap":  "No change",
        "accelerator":  "",
        "asset":  "Detailed documentation on how to Reset Transaction Data in cloud \u0026 overcome the Bugs for subsequent system use",
        "assetBusiness":  "Detailed documentation on how to Reset Transaction Data in cloud \u0026 overcome the Bugs for subsequent system use",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-013",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Taxation",
        "functionality":  "Taxation",
        "gapType":  "",
        "gapDetails":  "Product GAP on Implementation of Tax Engine",
        "businessGap":  "S/4HANA Cloud’s native tax engine has limited capabilities for complex, multi-jurisdiction tax scenarios, creating a gap for automated calculation, e‑invoicing, and real-time compliance.",
        "accelerator":  "Implementing Scope Item 43D -Brazil \u0026 Canada - https://rapid.sap.com/bp/#/browse/scopeitemversions/43D/S4CLD/2302/BR \u0026 Customising the Tax Engine to meet Customer Requirements",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-014",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Taxation",
        "functionality":  "Brazil Taxation",
        "gapType":  "",
        "gapDetails":  "Product GAP on Implementation of Tax Engine",
        "businessGap":  "",
        "accelerator":  "Implementation of following Scenarios for Brazil TE Implementation (Domestic \u0026 Interstate):\n\nProcurement of Material\nProcurement of Materials for Industrialisation\nProcurement of Materials for Consumption\n\nProcurement of Assets for Capitalisation\nProcurement of Electricity \n\nProcurement of Services\nProcurement of Imported Services\nProcurement scenarios for Leasing Contracts",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-015",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Taxation",
        "functionality":  "Brazil Taxation",
        "gapType":  "",
        "gapDetails":  "Product GAP on Brazil Taxation",
        "businessGap":  "Product GAP on Brazil Taxation , i.e.. XXXXXX, XXX…",
        "accelerator":  "",
        "asset":  "Comprehensive Documentation on Brazil Tax Reporting Required to implement Brazil Taxation",
        "assetBusiness":  "Comprehensive Documentation on Brazil Tax Reporting Required to implement Brazil Taxation",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-016",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Taxation",
        "functionality":  "Brazil Taxation",
        "gapType":  "",
        "gapDetails":  "Product GAP for Inbound Nota Fiscal (Electronic)",
        "businessGap":  "",
        "accelerator":  "Brazil NFe Integration with SEFAZ \u0026 E-Document Cockpit",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-017",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Taxation",
        "functionality":  "Brazil Taxation",
        "gapType":  "",
        "gapDetails":  "Product GAP on documentation required for Outbound Nota Fiscal",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Detailed documentation on setting up solution for Outbound Nota Fiscals using DRC (Licenses component) to connect to SEFAZ \u0026 use Nfe Monitor to manage the Outbound Nfe",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-018",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Taxation",
        "functionality":  "Brazil Tax Reporting",
        "gapType":  "",
        "gapDetails":  "Product GAP from SAP, missing information in Tax reporting to stay complaint in Brazil",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Documentation on using Advanced Compliance Reporting \u0026 Document \u0026 Reporting compliance to generate the Brazil Tax Reports along with the documentation to identify the blocks requiring manual updating because of the nature of Financial Posting in SAP.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-019",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Taxation",
        "functionality":  "USA Taxation",
        "gapType":  "",
        "gapDetails":  "Product GAP on Implementation of Tax Engine",
        "businessGap":  "",
        "accelerator":  "Implementing Scope Item 4Q2 - USA - https://rapid.sap.com/bp/#/scopeitems/4Q2 \u0026 Customising the Tax Engine to meet Customer Requirements",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-020",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Taxation",
        "functionality":  "USA Taxation",
        "gapType":  "",
        "gapDetails":  "Product GAP on Implementation of Tax Engine",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Detailed documentation on implementing in Sales Tax \u0026 Use Tax for Procurement \u0026 Sales scenarios",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-021",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-GL",
        "functionality":  "Review Booklet Designer",
        "gapType":  "",
        "gapDetails":  "GAP on how to utilise this to Enhance Customer reporting requirements",
        "businessGap":  "",
        "accelerator":  "Custom Layout for Review Booklets using Manage KPI \u0026 Reports app",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-022",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-GL",
        "functionality":  "Advanced FCV",
        "gapType":  "",
        "gapDetails":  "Advanced FCR does not work for currency translations",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Helping customers understand the design of Advanced FCV \u0026 missing translation functionalities",
        "assetBusiness":  "",
        "solution":  "Documentation explaining the manual option to translate the Historical \u0026 Non-Historical accounts at closing \u0026 Average Exchange Rate \n\nor utilising GR for Currency Translation using Data Monitor",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-023",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-GL",
        "functionality":  "Upload Journal Entries",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "Journal Upload for Currencies \u0026 Taxes",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-024",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-AP",
        "functionality":  "",
        "gapType":  "",
        "gapDetails":  "Aging Analysis report",
        "businessGap":  "",
        "accelerator":  "Custom App to provide this utilising SAP\u0027s existing CDS Views",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-025",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-AR",
        "functionality":  "",
        "gapType":  "",
        "gapDetails":  "Aging Analysis report",
        "businessGap":  "",
        "accelerator":  "Custom App to provide this utilising SAP\u0027s existing CDS Views",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-026",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-AA",
        "functionality":  "Asset History Sheet",
        "gapType":  "",
        "gapDetails":  "Asset history Sheet - There is no app that allows us to run the report for multiple company codes. Allows only single company code.",
        "businessGap":  "",
        "accelerator":  "Asset History Sheet for Multiple Company Codes",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-027",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-AA",
        "functionality":  "Scoping",
        "gapType":  "",
        "gapDetails":  "Scope Items 5KF (Addl depr area for AUC) and 5HG (Addl depr area for all asset classes) cannot be added after the initial scoping.",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Documentation of 5HG \u0026 5KF which leads to re-provisioning",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-028",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-AA",
        "functionality":  "Asset Balances",
        "gapType":  "",
        "gapDetails":  "Asset history Sheet - There is no app that allows us to run the report for multiple company codes. Allows only single company code.",
        "businessGap":  "",
        "accelerator":  "Asset History Sheet for Multiple Company Codes",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scripts to adopt to the developed Accelerators"
    },
    {
        "id":  "acc-029",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-AA",
        "functionality":  "CN41/42/43N in Cloud",
        "gapType":  "",
        "gapDetails":  "Missing functionality in Cloud",
        "businessGap":  "",
        "accelerator":  "Developed Custom Fiori App to replicate the functionalities of CN41/42/43N",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "Used I_EnterpriseProject\nI_EnterpriseProjectElement to build custom CN43N. \n\nNote: CN43N - just shows dimensional data",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-030",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-BAM",
        "functionality":  "Incoming Bank Statements",
        "gapType":  "",
        "gapDetails":  "Incoming Bank Statements (OT83) is replaced by new Processing rules in SAP which includes deprecation of Posting rules (restricted) \u0026 unavailable functionality - Search Strings",
        "businessGap":  "",
        "accelerator":  "Migration approach on how to translate Posting rules \u0026 Search strings with External Transaction types to create new Procssing rules. \nOvercoming SAP\u0027s limitation of preocessing rules",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "Comprehensive documentation to design new processing rules using External Transaction types from Bank, Posting Rules \u0026 Search strings in SAP\u0027",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-031",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-BAM",
        "functionality":  "BAM/Adv BAM",
        "gapType":  "",
        "gapDetails":  "Missing documnetation from SAP to help customers choose J78 (Additional license) or individual scope items for Payments Procssing \u0026 Bank Connectivity (2YM)",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Help customer choose BAM/Adv BAM based on Customer requirements which helps accelerate the implementation of Bank Account Management including Payment Procesing, Bank Communication Management",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-032",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-BAM",
        "functionality":  "API/MBC - Bank Connectivity",
        "gapType":  "",
        "gapDetails":  "Missing documentation from SAP as well as misleading documentation about the use of MBC for every customer as it carries a hefty licensing \u0026 Maintenance costs",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Outgoing Bank Statement - SWIFT/FILE/API Integration using 2YM",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-033",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-BAM",
        "functionality":  "API- Bank Connectivity",
        "gapType":  "",
        "gapDetails":  "Product GAP in S4 PC which doesn’t allow to out-of-Box api to connnect to Banks",
        "businessGap":  "",
        "accelerator":  "Incoming Bank Statement - SWIFT/FILE/API",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "Enable Custom Fiori which will use the IFLOWS to connect to the BANK API\u0027s to pull the required information",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-034",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-BAM",
        "functionality":  "APM \u0026 Integration",
        "gapType":  "",
        "gapDetails":  "GAPS on Implementing Advanced Payment Management in Cloud",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Comprehensive documentation to help customers choose the APM implementation on cloud \u0026 its integration with ERP \u0026 non ERP Products to integrate \u0026 pull data into SAP for Payment Processing.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-035",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-BAM/2-Tier",
        "functionality":  "Inetgartion for Payment Files",
        "gapType":  "",
        "gapDetails":  "Payment files integration from PC to SAP/Non-SAP Systems",
        "businessGap":  "",
        "accelerator":  "Developed an Integration using SAP BTP, Microservices to securely move the payment data from Cloud to SAP \u0026 Non-SAP systems",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "Detailed documentation enabling the details required to complete the integration with no external efforts",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-036",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-BAM/2-Tier",
        "functionality":  "Integration with SAP Instances",
        "gapType":  "",
        "gapDetails":  "Product GAP on how to communicate with additional SAP Intances for the customer",
        "businessGap":  "",
        "accelerator":  "Developed an Integration using MBC Connector (custom license to be created based on Customer request) which allows S4 PC \u0026 additional SAP instance to communicate \u0026 exchange data securely",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "Detailed documentation enabling the details required to complete the integration with no external efforts",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-037",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "FI-BAM",
        "functionality":  "Payment Reversals in Cloud",
        "gapType":  "",
        "gapDetails":  "SAP has disabled the option to auto reverse the payment files up on BCM rejection of Bank Rejections (PAIN.002 files).",
        "businessGap":  "",
        "accelerator":  "Developed a standard solution that allows us to automate the payment reversals for the affected transactions automatically using PAIN files \u0026 BCM",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "Detailed documentation enabling the details required to complete the integration with no external efforts.",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-038",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "REFX",
        "functionality":  "Leasing report to details list of Leasing Contracts",
        "gapType":  "",
        "gapDetails":  "No Sunch functionality exists in Cloud",
        "businessGap":  "",
        "accelerator":  "Lease Contracts - reporting requirements",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-039",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "REFX",
        "functionality":  "Cash Flow Leasing Report",
        "gapType":  "",
        "gapDetails":  "Missing Cashflow leasing report in SAP which provides details of multiple leasing contracts required for legalreporting requirements.",
        "businessGap":  "",
        "accelerator":  "Lease liability movement reports - multiple contracts",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-040",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "REFX",
        "functionality":  "Leasing Liabilities Movement Report",
        "gapType":  "",
        "gapDetails":  "Leasing Liabilities Movement Report  fr multiple leasing contracts",
        "businessGap":  "",
        "accelerator":  "Developed custom Fiori app to meet this requiremenst which essentially saves lot of manual effort to build an excel version which is prone to errors",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-041",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "CO-PCA",
        "functionality":  "",
        "gapType":  "",
        "gapDetails":  "Using, FAGL3KEH we can only do bank accounts and bank clearing accounts",
        "businessGap":  "",
        "accelerator":  "FAGL3KEH for PC Defaults in Public Cloud",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-042",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "CO-PCA",
        "functionality":  "",
        "gapType":  "",
        "gapDetails":  "Lack of Documentation on Profit center accounting design to support the Management Reporting",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Comprehensive PCA options to outline the Management reporting needs based on Customer \u0026 Industry of business",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-043",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "CO-PCA",
        "functionality":  "Profit Centre Re-Organization",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Comprehensive design \u0026 documnetation option on how to setup \u0026 use Profit Centre Reorganisation with having to duplicate PC setup, avoid manual efforts to transfer data to new Profit Centres",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-044",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "CO-PCA",
        "functionality":  "",
        "gapType":  "",
        "gapDetails":  "Lack of use cases on Segment deisgn for PC as its one of mandatory field in PC",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Comprehensive PCA \u0026 Segment design options to outline the Management reporting needs based on Customer \u0026 Industry of business",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-045",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "CO-CCA",
        "functionality":  "",
        "gapType":  "",
        "gapDetails":  "Lack of Documentation on Cost center accounting design to support the Management Reporting",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Comprehensive CCA options to outline the Management reporting needs based on Customer \u0026 Industry of business",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-046",
        "include":  false,
        "module":  "Manufacturing",
        "productArea":  "PP",
        "functionality":  "Variance Report",
        "gapType":  "",
        "gapDetails":  "Product GAP from SAP",
        "businessGap":  "",
        "accelerator":  "Custom Fiori app using BTT leveraging Data from Marginal Analysis to build a comprehensive reporting option for Variances",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-047",
        "include":  false,
        "module":  "Manufacturing",
        "productArea":  "PP",
        "functionality":  "Product Profitability Report",
        "gapType":  "",
        "gapDetails":  "Product GAP from SAP",
        "businessGap":  "",
        "accelerator":  "Custom Fiori app using Contribution Maragin reporting logic, Global Hierarchies to build a comprehensive reporting option for Variances",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-048",
        "include":  false,
        "module":  "Consolidation",
        "productArea":  "GR",
        "functionality":  "GRDC",
        "gapType":  "",
        "gapDetails":  "Missing Documentation required for Implementation",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Comprehensive implementtaion documenttaion in Technical, Integration \u0026 Functional areas required to Implement GRDC.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-049",
        "include":  false,
        "module":  "Consolidation",
        "productArea":  "GR",
        "functionality":  "GRDC",
        "gapType":  "",
        "gapDetails":  "Missing fields in API GL Line Item Read required for Consolidations in GR",
        "businessGap":  "",
        "accelerator":  "GRDC API - GL_LINEITEMSREAD extended with WBS fields to support GR requirements",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-050",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "MRM",
        "functionality":  "MRM",
        "gapType":  "",
        "gapDetails":  "Missing Documentation required for Implementation",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Market Rates Management",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-051",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Blackline",
        "functionality":  "Blackline",
        "gapType":  "",
        "gapDetails":  "Missing Documentation required for Implementation",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Blackline",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-052",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Data Replication",
        "functionality":  "Data Replication from PC to On-prem",
        "gapType":  "",
        "gapDetails":  "Missing option to replicate data to Subsequent Systems",
        "businessGap":  "",
        "accelerator":  "The data like BP, CC, PC and WBS elements are replicated with Odata API and NWT",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-053",
        "include":  false,
        "module":  "Finance \u0026 Controlling",
        "productArea":  "Analysis for Office",
        "functionality":  "Analysis for Office",
        "gapType":  "",
        "gapDetails":  "Missing Documentation required for Implementation",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Comprehensive implementtaion documenttaion in Technical, Integration \u0026 Functional areas required to Implement AO.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-054",
        "include":  false,
        "module":  "Successfactors",
        "productArea":  "People/HR",
        "functionality":  "S4 PC Integration to SF",
        "gapType":  "",
        "gapDetails":  "Gaps in Time Management \u0026 Absence Handling",
        "businessGap":  "",
        "accelerator":  "Absence records from SF Employee Central do not seamlessly reflect in S/4HANA Public Cloud for workforce planning.\nTime tracking data from SF Time Management require additional configurations to align with S/4HANA payroll processing.",
        "asset":  "Comprehensive implementtaion documenttaion in Technical, Integration \u0026 Functional areas required to Implement AO.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-055",
        "include":  false,
        "module":  "Successfactors",
        "productArea":  "People/HR",
        "functionality":  "Contractor Management Solution",
        "gapType":  "",
        "gapDetails":  "Contractor Management Solution",
        "businessGap":  "",
        "accelerator":  "Our Contractor Management Solution streamlines the end-to-end contractor request and approval process, enabling seamless collaboration between vendors and in-house mobilization teams.\n\nVendor Portal: Vendors can log in to submit contractor requests with relevant details.\nReview \u0026 Approval Workflow: The in-house mobilization team reviews, approves, or rejects requests within a structured workflow.\nSeamless Integration: Approved requests are automatically integrated from SAP S/4HANA Public Cloud to SuccessFactors, ensuring accurate workforce data synchronization.\nThis solution enhances efficiency, reduces manual effort, and ensures compliance, making contractor onboarding and workforce management smoother and more transparent.",
        "asset":  "Comprehensive implementtaion documenttaion in Technical, Integration \u0026 Functional areas required to Implement AO.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-056",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Procurement/Logistics",
        "functionality":  "S4 PC Integration to Ariba",
        "gapType":  "",
        "gapDetails":  "Support for advanced procurement scenarios like complex contract management, multi-tier supplier collaboration, or industry-specific workflows are not fully covered.",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Detailed implementtaion documentation covering Technical, Integration \u0026 Functional aspects.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-057",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Procurement/Logistics",
        "functionality":  "S4 PC Integration to Fieldglass",
        "gapType":  "",
        "gapDetails":  "Standard connectors have limitation for seamless integrations for Statement of Work (SOW) contracts and services procurement scenarios.",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Detailed implementtaion documentation covering Technical, Integration \u0026 Functional aspects.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-058",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Procurement/Logistics",
        "functionality":  "Inventory Track and Trace",
        "gapType":  "",
        "gapDetails":  "Live tracking and tracing solution",
        "businessGap":  "",
        "accelerator":  "The BTP-Based Inventory Live Track and Trace Solution enables real-time tracking of shipments from delivery centers to site warehouses, ensuring end-to-end visibility across the supply chain. By leveraging SAP Business Technology Platform (BTP), this solution integrates with logistics networks, IoT-enabled tracking devices, and ERP systems to provide live status updates, predictive insights, and exception alerts.",
        "asset":  "Detailed implementtaion documentation covering Technical, Integration \u0026 Functional aspects.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-059",
        "include":  false,
        "module":  "EAM",
        "productArea":  "Assets/PM",
        "functionality":  "OMM",
        "gapType":  "",
        "gapDetails":  "Optimised Maintenance Management",
        "businessGap":  "",
        "accelerator":  "Our BTP-Based Asset Management Solution provides a seamless integration of SAP S/4HANA Cloud Maintenance data with SuccessFactors Employee Attendance/Absence records and training schedules from SuccessFactors LMS, while also tracking contractor availability through third-party integrations. This unified approach delivers a comprehensive, real-time dashboard at the site and work center levels, empowering maintenance teams with accurate workforce insights for efficient task scheduling. By ensuring full visibility into employee availability, training compliance, and contractor resources, the solution optimizes resource planning, enhances operational efficiency, and minimizes downtime.",
        "asset":  "Detailed implementtaion documentation covering Technical, Integration \u0026 Functional aspects.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-060",
        "include":  false,
        "module":  "Custom Developments",
        "productArea":  "Integration Suite/API Hub",
        "functionality":  "APIs",
        "gapType":  "",
        "gapDetails":  "Additional custom APIs for identified gaps.",
        "businessGap":  "",
        "accelerator":  "Due to limitations in standard out-of-the-box APIs, we offer a curated set of enhanced APIs designed to bridge functionality gaps and support advanced business scenarios. These APIs are pre-packaged, optimized, and ready for deployment, ensuring seamless integration, improved performance, and faster implementation.",
        "asset":  "Detailed implementtaion documentation covering Technical, Integration \u0026 Functional aspects.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-061",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "PO tax code determination",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "since PC does not allow tax-related tax code determination condition record, we have to use the system enhancement to automatically determines related tax code when a new PO is created",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-062",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "PO Tax Jd Determination",
        "gapType":  "",
        "gapDetails":  "PO Tax Jurisdiction Code determination upon delivery address change",
        "businessGap":  "",
        "accelerator":  "As PC does not allow automatic tax jurisdiction code re-determination as soon as the delivery address is updated, a system enhancement was implemented",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  "Updated Test Scipts to adopt to the developed Accelarators"
    },
    {
        "id":  "acc-063",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Delivery Address issue on Tax Engine",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Delivery Address not sent to External Tax Engine while creating a new PO using \"Manage Purchase Order\" - Contrary to the \"Create Purchase Order - Advanced\" App where the delivery address is sent to External Tax Engine as part of request payload, if the PO is created via standard \"Manage Purchase Order\" App, the delivery address is not sent.  Instead it is the plant address that is included in the request payload to External Tax Engine",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-064",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Business Transation Type",
        "gapType":  "",
        "gapDetails":  "Business Transaction Type is not sent to External Tax Engine during SES / goods receipt posting",
        "businessGap":  "",
        "accelerator":  "Contrary to the PO and invoice creation where the Business Transaction Type is included in the request payload, the same information is not sent to ONESOURCE during SES / goods receipt posting.  Hence, enhancement is required",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-065",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "PO Output",
        "gapType":  "",
        "gapDetails":  "Unable to manually delete the PO output upon creation",
        "businessGap":  "",
        "accelerator":  "Contrary to OP where PO creators are allowed to manually remove the output type, this technical flexibility is not allowed in PC and therefore, require the system enhancement",
        "asset":  "",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-066",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "RFQ",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "When converting the awarded RFQ / quotation to purchase contract, the non-awarded RFQ / quotation item was also copied with zero quantity",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-067",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Requirement Tracking Number",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "The \"Requirement Tracking Number\" field is missing the \"Manage Purchase Order\" App although this field is available in the \"Manage Purchase Requisition - Professional\" and \"Create Purchase Order - Advanced\" App",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-068",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Technical Limitatatoins on Cloud",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "SAP strictly controls the settings of the standard document types such as field status, number ranges etc..., it is not feasible to customize as per business requirements",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-069",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Standard Fiori Apps such as \"My Purchase Requisition - New\" or \"Manage Purchase Requisition - Professional\" or \"Manage Purchase Order\" are the simpler version of the WEB-GUI Transactions, business can\u0027t expect the same level of functionalities",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-070",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Fiori Apps are defined on the role basis, hence there are several Apps that are used for the same data object such as \"My Purchase Requisition - New\"; \"Manage Purchase Requisition - Professional\"; \"Create Purchase Requisition - Advanced\", it is important business should know which App is suitable for each business role",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-071",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "As PC is built on the basis of Best Practices, there is limited opportunity to implement as many system enhancements as possible in PC as compared to OP.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-072",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Automatic PO Acknowledgement",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "If business wishes to automate this process, it will require the SBPA (SAP Build Process  Automation) / RPA (Robotic Process Automation) where the standard API CE_SUPPLIERCONFIRMATION_0001 (https://help.sap.com/docs/SAP_S4HANA_CLOUD/bb9f1469daf04bd894ab2167f8132a1a/b2c94ca7660d4838b2518833fe2b539d.html?version=2502.500) should be used\nSAP RPA Tool - Mass Purchase Order Confirmation - https://api.sap.com/package/eu10.storecontentdevacc.masspurchaseorderconfirmations/overview",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-073",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Automatic Update Advance Shipping Notification",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "If business wishes to automate this process, it will require the SBPA / RPA where the standard API API_INBOUND_DELIVERY_SRV_0002 (https://help.sap.com/docs/SAP_S4HANA_CLOUD/588780cab2774a7ab9fffca3a7f919fe/d10ec16c462a44a7be6c6721c9bb0a93.html?locale=en-US) is used\nSAP RPA - Creation of Inbound Delivery (4QK) - https://api.sap.com/package/1bf712197cc54c41b4c5f2496341a6ce/overview",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-074",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Mass uploading of inhouse Catalogs",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Custom App development",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-075",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Mass uploading of purchase requisitions",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "SAP RPA - Create Purchase Requisitions from Excel (48M) - https://api.sap.com/package/4cf34f5d2ab043b8b64d741851349b91/overview",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-076",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Automatic notification of superseded materials in purchasing contract",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Requirement is -  once the material is identified as \u0027Discontinued\u0027 in the Product Master, the purchasing team will have to be notified and review the current Purchase Contract in place and take approriate action to reduce/delete.\nCan be achieved through situation handling",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-077",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Automatic generation of material purchase order items report with delivery due date and communication to the purchasing team",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "Custom report to send to Vendor on and when required.",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-078",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Off-site Receipt Process - Material Warehouse Disposal Request Form",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "To support the Off-site Material Disposal Process, the Material Warehouse Disposal Request Form should be developed in BTP (including approval workflow)",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-079",
        "include":  false,
        "module":  "Quality Management",
        "productArea":  "QM",
        "functionality":  "Mass creation of Quality Info Records to mass update the \"Quality Inspection Required\" flag for all materials which are supplied by a vendor who has a poor quality record",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "The SAP RPA Scope Item \"6NX\" can be used to cater for this business requirement - https://api.sap.com/package/d6a7908114dd495e960c6b4ba3ea5e96/overview",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-080",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "System validation to ensure purchase order with multiple line items can only be created with a single plant",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "It is suggested that the standard BAdI \"BD_MMPUR_FINAL_CHECK_PO\" (Enhancement Spot \"ES_MMPUR_PROCESS_PO_CLOUD\" - Interface \"IF_EX_MMPUR_FINAL_CHECK_PO\") or \"MM_PUR_S4_PO_CHECK_ALL_ITEMS\" (Enhancement Spot \"ES_MMPUR_PROCESS_PO_CLOUD\" - Interface \"IF_MM_PUR_S4_PO_CHECK_ALL_ITMS\") should be used to cater for this business requirement -\nhttps://api.sap.com/badi/BD_MMPUR_FINAL_CHECK_PO\nhttps://api.sap.com/badi/MM_PUR_S4_PO_CHECK_ALL_ITEMS",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-081",
        "include":  false,
        "module":  "Supply Chain",
        "productArea":  "Supplychain/Warehouse",
        "functionality":  "Automatic default of the Production Order-related Reservation to the \"Requirement Tracking Number\" field when stock transort requisition is created through MRP run",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "It is suggested that the standard BAdI \"PPH_MRP_PURREQ_CFL\" should be used to cater for this business requirement -\nhttps://help.sap.com/docs/SAP_S4HANA_CLOUD/2bba750d1e124e1ea2a039bb1cd9b6c5/c20b8cfa8000468d86a005ec6d03259f.html",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-082",
        "include":  false,
        "module":  "Procurement",
        "productArea":  "Purchasing",
        "functionality":  "Update material price from Purchasing contract to PR",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "implemented for BR",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    },
    {
        "id":  "acc-083",
        "include":  false,
        "module":  "Flexible Workflow",
        "productArea":  "Workflow",
        "functionality":  "Restrict approval workflow retrigger when the PO value is decreased or PO flagged with delivery completion indicator (DCI)",
        "gapType":  "",
        "gapDetails":  "",
        "businessGap":  "",
        "accelerator":  "",
        "asset":  "implemented for BR",
        "assetBusiness":  "",
        "solution":  "",
        "testScript":  ""
    }
];

